main: cc.altoya.progression.App
name: progression
version: 1.0
api-version: 1.21.4
description: Progression plugin

commands:
  experience:
    description: Experience system
    usage: /experience {subcommand} {var}
    tab-completer: cc.altoya.progression.Experience.ExperienceTabCompleter
  gear:
    description: Gear system
    usage: /gear {subcommand} {var}
    tab-completer: cc.altoya.progression.Experience.GearTabCompleter
