main: cc.altoya.techtree.App
name: techtree
version: 1.0
api-version: 1.21.4
description: TechTree plugin

commands:
  tech:
    description: TechTree system
    usage: /tech {subcommand} {var}
    tab-completer: cc.altoya.techtree.Tech.TechTabCompleter
