main: cc.altoya.progression.App
name: progression
version: 1.0
api-version: 1.21.1
description: Progression plugin

commands:
  city:
    description: Domains
    usage: /city {subcommand} {var}
    tab-completer: cc.altoya.settlements.City.CityTabCompleter
